services:
  postgres:
    image: postgres:16
    container_name: wikipediagolf-dev-db
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.local
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: tagbox-dev-db-data
